<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\version.targets" />

  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SnesGame.CLR\SnesGame.CLR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnaryHeap.Mosaic">
      <HintPath>..\dependencies\UnaryHeap\UnaryHeap.Mosaic.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
