<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\version.targets" />

  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>graphpaper.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <StartupObject>GraphPaper.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnaryHeap.DataType">
      <HintPath>..\dependencies\UnaryHeap\UnaryHeap.DataType.dll</HintPath>
    </Reference>
    <Reference Include="UnaryHeap.Graph">
      <HintPath>..\dependencies\UnaryHeap\UnaryHeap.Graph.dll</HintPath>
    </Reference>
    <Reference Include="UnaryHeap.GUI">
      <HintPath>..\dependencies\UnaryHeap\UnaryHeap.GUI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>