<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\version.targets" />

  <PropertyGroup>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>patchwork.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <StartupObject>Patchwork.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnaryHeap.GUI">
      <HintPath>..\dependencies\UnaryHeap\UnaryHeap.GUI.dll</HintPath>
    </Reference>
    <Reference Include="UnaryHeap.Mosaic">
      <HintPath>..\dependencies\UnaryHeap\UnaryHeap.Mosaic.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>