name: Continuous Deployment

on:
  push:

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Lint tool
      run: dependencies\UnaryHeap\Lintroller.exe . 98 text

    - name: Nuget Restore
      run: nuget restore SnesGame.sln

    - name: Build 32-bit
      run: msbuild /p:Configuration=Release /p:Platform=x86
      
    - name: Build 64-bit
      run: msbuild /p:Configuration=Release /p:Platform=x64
